app:
  id: 1
  name: GopherAssistant_bot
  log_level: info
  is_log_json: true

bot:
  token: ""
  timeout: 1s

gpt4all:
  token: "g4a-oAVXy88GW5d4n5FvstCoyi5wBjPPDCE6Fif" # Токен GPT4All
  url: "https://api.gpt4-all.xyz/v1"             # URL API GPT4All

metrics:
  enabled: false
  host: ""
  port: 0

tracing:
  enabled: false
  host: ""
  port: 0
